apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "union-operator.fullname" . }}
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
data:
  config.yaml: |
    union:
      connection:
        host: {{ tpl (include "union-operator.grpcUrl" . | toString) $ }}
      auth:
        type: ClientSecret
        clientId: {{ tpl (.Values.union.appId | toString) $ }}
        clientSecretLocation: /etc/union/secret/app_secret
        authorizationMetadataKey: "flyte-authorization"
        tokenRefreshWindow: 5m
    operator:
      enabled: {{ tpl (.Values.union.enabled | toString) $ }}
      enableTunnelService: {{ tpl (.Values.union.enableTunnelService | toString) $ }}
      clusterId:
        organization: {{ include "union-operator.org" . }}
      dependenciesHeartbeat:
        propeller:
          endpoint: http://flytepropeller.{{ include "union-operator.namespace" . }}.svc.cluster.local:{{ print (index .Values.union.configmap.core.propeller "prof-port") }}
        proxy:
          endpoint: http://union-operator-proxy.{{ include "union-operator.namespace" . }}.svc.cluster.local:{{ print (index .Values.union.proxy "prof-port") }}
{{- if .Values.union.unionoperatorSparkHistoryServer.enabled }}
        spark-hs:
          endpoint: http://union-operator-spark-hs.{{ include "union-operator.namespace" . }}.svc.cluster.local:{{ print (index .Values.union.proxy "prof-port") }}
{{- end }}
      clusterData:
        appId: {{ tpl (.Values.union.appId | toString) $ }}
        cloudHostName: {{ tpl (include "union-operator.cloudHostName" . | toString) $ }}
        metadataBucketPrefix: {{ tpl (.Values.union.metadataBucketPrefix | toString) $ }}
        bucketName:  {{ tpl (include "union-operator.bucket" . | toString) $ }}
        bucketRegion: {{ tpl (include "union-operator.bucketRegion" . | toString) $ }}
        userRoleKey: {{ tpl (.Values.union.userRoleAnnotationKey | toString) $ }}
        userRole: {{ tpl (.Values.union.userRoleAnnotationValue | toString) $ }}
        storageType: {{ tpl (.Values.union.storage.type | toString) $ }}
        gcpProjectId: {{ tpl (include "union-operator.gcpProjectId" . | toString) $ }}
      collectUsages:
        enabled: {{ tpl (.Values.union.collectUsages.enabled | toString) $ }}
{{- if  .Values.union.storage.customStorageConfig}}
        customStorageConfig: {{ tpl (.Values.union.storage.customStorageConfig | toString) $ }}
{{- end }}
  logger.yaml: |
    logger:
      level: 4
      show-source: true
{{- with .Values.union.unionoperator.configmapOverrides }}
  config-overrides.yaml: |
  {{ toYaml . | nindent 4 }}
{{- end }}
  storage.yaml: | {{ tpl (include "union-storage" .) $ | nindent 4 }}
