apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "union-operator.fullname" . }}
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
data:
  config.yaml: |
    union:
      connection:
        host: {{ tpl (include "union-operator.grpcUrl" . | toString) $ }}
      auth:
        type: ClientSecret
        clientId: {{ tpl (.Values.union.appId | toString) $ }}
        clientSecretLocation: /etc/union/secret/app_secret
    operator:
      clusterId:
        organization: {{ include "union-operator.org" . }}
{{- with .Values.union.unionoperator.configmapOverrides }}
  config-overrides.yaml: |
  {{ toYaml . | nindent 4 }}
{{- end }}
