apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "union-operator.fullname" . }}-proxy
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.union.proxy.autoscaling.enabled }}
  replicas: {{ .Values.union.proxy.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.union.unionoperator.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "proxy.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "union-operator.fullname" . }}
      priorityClassName: {{ .Values.union.unionoperator.priorityClassName }}
      {{- with .Values.union.unionoperator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "union-operator.serviceAccountName" . }}-proxy
      securityContext:
        {{- toYaml .Values.union.unionoperator.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-proxy
          securityContext:
            {{- toYaml .Values.union.unionoperator.securityContext | nindent 12 }}
          image: "{{ .Values.union.unionoperator.image.repository }}:{{ .Values.union.unionoperator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.union.unionoperator.image.pullPolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            {{- toYaml .Values.union.proxy.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/union/config
              name: config-volume
          args:
            - operator
            - proxy
            - --config
            - /etc/union/config/*.yaml
          ports:
            - name: http
              containerPort: 8089
              protocol: TCP
            - name: debug
              containerPort: 10254
              protocol: TCP
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      {{- with .Values.union.unionoperator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.union.unionoperator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.union.unionoperator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
