apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "union-operator.fullname" . }}
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
spec:
  {{- if not .Values.union.unionoperator.autoscaling.enabled }}
  replicas: {{ .Values.union.unionoperator.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "union-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        configChecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 | quote }}
      {{- with .Values.union.unionoperator.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "union-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.union.unionoperator.additionalLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      priorityClassName: {{ .Values.union.unionoperator.priorityClassName | default "system-cluster-critical" }}
      {{- with .Values.union.unionoperator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "union-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.union.unionoperator.podSecurityContext | nindent 8 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "union-operator.fullname" . }}
        - name: secret-volume
          secret:
            secretName: {{ .Values.union.unionoperator.secretName}}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.union.unionoperator.securityContext | nindent 12 }}
          image: "{{ .Values.union.unionoperator.image.repository }}:{{ .Values.union.unionoperator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.union.unionoperator.image.pullPolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            {{- toYaml .Values.union.unionoperator.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/union/config
              name: config-volume
            - mountPath: /etc/union/secret
              name: secret-volume
          env:
            - name: CLUSTER_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "union-operator.fullname" . }}-cluster-name
                  key: cluster_name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEPLOYMENT_NAME
              value: {{ include "union-operator.fullname" . }}
            {{- with .Values.union.unionoperator.podEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          args:
            - operator
            - serve
            - --config
            - /etc/union/config/*.yaml
            - --operator.clusterId.name
            - "$(CLUSTER_NAME)"
            - --operator.tunnel.k8sSecretName
            - {{ .Values.union.unionoperator.secretName }}
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
            - name: http
              containerPort: 8089
              protocol: TCP
            - name: debug
              containerPort: 10254
              protocol: TCP

        {{- if .Values.union.enableTunnelService }}
        - name: "tunnel"
          securityContext:
            {{- toYaml .Values.union.unionoperator.securityContext | nindent 12 }}
          image: cloudflare/cloudflared:2024.6.1
          imagePullPolicy: {{ .Values.union.unionoperator.image.pullPolicy }}
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - $(TUNNEL_TOKEN)
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.union.unionoperator.secretName }}
                  key: tunnel_token
                  optional: true
        {{- end }}
      {{- with .Values.union.unionoperator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.union.unionoperator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.union.unionoperator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
