apiVersion: v1
kind: Secret
metadata:
  name: {{ include "union-operator.fullname" . }}
type: Opaque
stringData:
  app_secret: {{ tpl .Values.union.appSecret . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "union-operator.fullname" . }}-cluster-name
type: Opaque
{{- $previous := lookup "v1" "Secret" .Release.Namespace (printf "%v-cluster-name" (include "union-operator.fullname" .)) }}
data:
  {{- if .Values.union.clusterName }}
  cluster_name: {{ .Values.union.clusterName | b64enc | quote }}
  {{- else if $previous }}
  cluster_name: {{ $previous.data.cluster_name }}
  {{- else }}
  cluster_name: {{ (include "clusterName" .) | b64enc | quote }}
  {{- end }}
