{{- if .Values.union.proxy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "union-operator.serviceAccountName" . }}-proxy
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
  {{- with .Values.union.proxy.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "union-operator.serviceAccountName" . }}-proxy
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
  {{- with .Values.union.proxy.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - '*'
    resources:
      - events
      - flyteworkflows
      - pods/log
      - pods
      - rayjobs
      - resourcequotas
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "union-operator.serviceAccountName" . }}-proxy
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
  {{- with .Values.union.proxy.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "union-operator.serviceAccountName" . }}-proxy
subjects:
  - kind: ServiceAccount
    name: {{ include "union-operator.serviceAccountName" . }}-proxy
    namespace: {{ template "flyte.namespace" . }}
{{- end }}
