apiVersion: v1
kind: Service
metadata:
  name: {{ include "union-operator.fullname" . }}
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.union.unionoperator.service.type }}
  ports:
    - port: {{ .Values.union.unionoperator.service.port }}
      targetPort: debug
      protocol: TCP
      name: debug
  selector:
    {{- include "union-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "flytepropeller.name" . }}
spec:
  ports:
    - port: {{ index .Values.union.configmap.core.propeller "prof-port" }}
  selector:
    {{- include "flytepropeller.selectorLabels" . | nindent 4 }}
