{{- if .Values.union.unionoperator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "union-operator.serviceAccountName" . }}
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
  {{- with .Values.union.unionoperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "union-operator.serviceAccountName" . }}
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
  {{- with .Values.union.unionoperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - '*'
    resources:
      - secrets
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "union-operator.serviceAccountName" . }}
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
  {{- with .Values.union.unionoperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "union-operator.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "union-operator.serviceAccountName" . }}
    namespace: {{ template "flyte.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "union-operator.serviceAccountName" . }}
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
  {{- with .Values.union.unionoperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  # Allow Access to all resources under flyte.lyft.com
  - apiGroups:
      - flyte.lyft.com
    resources:
      - flyteworkflows
      - flyteworkflows/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
      - post
      - deletecollection
  - apiGroups:
      - '*'
    resources:
      - resourcequotas
      - pods
      - configmaps
      - podtemplates
      - nodes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "union-operator.serviceAccountName" . }}
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
  {{- with .Values.union.unionoperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "union-operator.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "union-operator.serviceAccountName" . }}
    namespace: {{ template "flyte.namespace" . }}
{{- end }}
