{{- if .Values.union.unionoperatorSparkHistoryServer.enabled -}}
{{- if .Values.union.unionoperatorSparkHistoryServer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "unionoperatorSparkHistoryServer.serviceAccountName" . }}
  labels:
    {{- include "unionoperatorSparkHistoryServer.labels" . | nindent 4 }}
  {{- with .Values.union.unionoperatorSparkHistoryServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}