{{- if .Values.taskNamespaceNetworkPolicy.enabled }}
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: {{ include "union-operator.fullname" . }}-task-ns-netpol
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
spec:
  namespaceSelector: {{ required "Namespace selector is required for identifying task namepaces!" .Values.taskNamespaceNetworkPolicy.selector }}
  types:
  - Egress
  egress:
  # If blocking internal IPs, explicitly allow access to kube-dns and kube-api
  {{- if .Values.taskNamespaceNetworkPolicy.blockInternalIPs }}
  - action: Allow
    destination:
      services:
        name: kube-dns
        namespace: kube-system
  - action: Allow
    destination:
      services:
        name: kubernetes
        namespace: default
  - action: Deny
    destination:
      nets:
      # Capture all private IP CIDR blocks
      # See: https://www.arin.net/reference/research/statistics/address_filters/
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
  {{- end }}
  # Disables access to GKE / GCP Instance Metadata Server (IMDS)
  # See https://cloud.google.com/kubernetes-engine/docs/how-to/network-policy#network-policy-and-workload-identity
  {{- if .Values.taskNamespaceNetworkPolicy.blockIMDS }}
  - action: Deny
    destination:
      nets:
      - 169.254.169.252/32
      - 169.254.169.254/32
  {{- end }}
  - action: Allow
    destination:
      nets:
      - 0.0.0.0/0
{{- end }}
