{{- if .Values.flyte.flytepropeller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flytepropeller
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.flyte.flytepropeller.replicaCount }}
  selector:
    matchLabels: {{ include "flytepropeller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        configChecksum: {{ include (print .Template.BasePath "/flyte/propeller/configmap.yaml") . | sha256sum | trunc 63 | quote }}
        {{- with .Values.flyte.flytepropeller.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels: {{ include "flytepropeller.labels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 1001
        fsGroupChangePolicy: "Always"
      containers:
      - command:
        - flytepropeller
        - --config
        - {{ .Values.flyte.flytepropeller.configPath }}
        {{- with .Values.flyte.flytepropeller.extraArgs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: "{{ .Values.flyte.flytepropeller.image.repository }}:{{ .Values.flyte.flytepropeller.image.tag }}"
        imagePullPolicy: "{{ .Values.flyte.flytepropeller.image.pullPolicy }}"
        name: flytepropeller
        ports:
        - containerPort: 10254
        resources: {{ toYaml .Values.flyte.flytepropeller.resources | nindent 10 }}
        volumeMounts:
          - name: config-volume
            mountPath: /etc/flyte/config
          - name: auth
            mountPath: /etc/secrets/
      serviceAccountName: {{ template "flytepropeller.name" . }}
      volumes:
      - configMap:
          name: flyte-propeller-config
        name: config-volume
      - name: auth
        secret:
          secretName: flyte-propeller-auth
      {{- with .Values.flyte.flytepropeller.nodeSelector }}
      nodeSelector: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.flyte.flytepropeller.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.flyte.flytepropeller.tolerations }}
      tolerations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
{{- end }}
