{{- if .Values.resourcequota.create }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: union-critical-pods
spec:
  hard:
    pods: "20"
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-cluster-critical
{{- end }}
