apiVersion: v1
kind: ConfigMap
metadata:
  name: flyte-propeller-config
  namespace: {{ .Release.Namespace }}
data:
{{- with .Values.config.admin }}
  admin.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.config.catalog }}
  catalog.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.config.catalog_cache }}
  catalog_cache.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.config.copilot }}
  copilot.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.config.core }}
  core.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.config.enabled_plugins }}
  enabled_plugins.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
  k8s.yaml: | {{ tpl (include "k8s.plugins" .) $ | nindent 4 }}
  logger.yaml: |
{{- with .Values.config.logger }}
    logger: {{ tpl (toYaml .) $ | nindent 6 }}
{{- end }}
{{- with .Values.config.qubole }}
  qubole.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.config.resource_manager }}
  resource_manager.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- if .Values.sparkoperator.enabled }}
{{- with .Values.sparkoperator.plugin_config }}
  spark.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
{{- if .Values.databricks.enabled }}
{{- with .Values.databricks.plugin_config }}
  databricks.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
{{- with .Values.config.task_logs }}
  task_logs.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- if .Values.flyteagent.enabled }}
{{- with .Values.flyteagent.plugin_config }}
  agent_service.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
  storage.yaml: | {{ tpl (include "storage" .) $ | nindent 4 }}
