union:
  enableTunnelService: true
  cloudUrl: dns:///playground.hosted.unionai.cloud
  appId: abcdef
  appSecret: ghijklm
  metadataBucketPrefix: s3://opencompute-staging-sample-tenant
  storage:
    # -- Sets the storage type. Supported values are sandbox, s3, gcs and custom.
    type: s3
    bucketName: opencompute-production-sample-tenant
    # -- settings for storage type s3
    s3:
      region: us-east-2
    # -- settings for storage type gcs
    gcs:
    # -- GCP project ID. Required for storage type gcs.
    # projectId:
    # -- Settings for storage type custom. See https://github:com/graymeta/stow for supported storage providers/settings.
    custom: { }

  flytepropeller:
    # -- Configuration for service accounts for FlytePropeller
    serviceAccount:
      # -- Should a service account be created for FlytePropeller
      create: true
      # -- Annotations for ServiceAccount attached to FlytePropeller pods
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::479331373192:role/opencompute-production-sample-tenant-role
      # -- ImapgePullSecrets to automatically assign to the service account
      imagePullSecrets: { }

  unionoperator:
    priorityClassName: "system-cluster-critical"
    replicaCount: 1

    image:
      repository: public.ecr.aws/p0i0a9q8/unionoperator
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "458f9abd0b2dd2277059dc88709f4e251679918b" # UNION_OPERATOR_TAG

    imagePullSecrets: [ ]
    nameOverride: ""
    fullnameOverride: ""

    serviceAccount:
      # Specifies whether a service account should be created
      create: true
      # Annotations to add to the service account
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::479331373192:role/opencompute-production-sample-tenant-role
      # The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: ""

  unionoperatorSparkHistoryServer:
    enabled: false
