union:
  enableTunnelService: false
  cloudUrl: https://playground.hosted.unionai.cloud
  appId: abcdef
  metadataBucketPrefix: "gs://my-gcs-bucket-prod"
  userRoleAnnotationKey: iam.gke.io/gcp-service-account
  userRoleAnnotationValue: "<Operator IAM Permission>"
  storage:
    type: "gcs"
    bucketName: "my-gcs-bucket-prod"
    bucketRegion: "us-west1"
    gcs:
      projectId: "GOOGLE_TEST"
  flytepropeller:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account : "<Propeller IAM Permission>"
  unionoperator:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account : "<Propeller IAM Permission>"
  unionoperatorSparkHistoryServer:
    enabled: false
  objectStore:
    resources:
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      limits:
        cpu: "4"
        ephemeral-storage: 500Mi
        memory: "10Gi"
      requests:
        cpu: "4"
        ephemeral-storage: 500Mi
        memory: "10Gi"
