union:
  cloudUrl: dns:///playground.hosted.unionai.cloud
  appId: abcdef
  appSecret: ghijklm
  metadataBucketPrefix: s3://my-s3-bucket-prod
  storage:
    type: "s3"
    bucketName: my-s3-bucket-prod
    s3:
      region: "us-east-2"