{{- if .Values.union.unionoperatorMonitoring.enabled -}}
{{- if .Values.union.unionoperatorMonitoring.dcgmExporter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "unionoperatorMonitoring.dcgmExporter.serviceAccountName" . }}
  namespace: kube-system
  labels:
    {{- include "unionoperatorMonitoring.dcgmExporter.labels" . | nindent 4 }}
  {{- with .Values.union.unionoperatorMonitoring.dcgmExporter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}