{{- if .Values.union.unionoperatorMonitoring.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "union-operator.fullname" . }}-prometheus
  labels:
    {{- include "unionoperatorMonitoring.prometheus.labels" . | nindent 4 }}
data:
  # Current config support scraping from configured kube state metrics service which serves request and limit metrics of
  # all the pods running in the data plane.(We will later restrict this to serve only from configured namespaces where
  # user pods are running). Also apart from request and limit it scrapes other metrics which come out of the box by installing
  # the service.We will further refine them to set of useful metrics that should be scraped in next iteration.
  # This installation of prometheus doesn't support scaling or retention and would be taken as immediate next step.
  # The scrape interval is of 15 sec from state metrics endpoint.
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
    rule_files:
      - rules.yml
    scrape_configs:
      - job_name: 'kube-state-metrics'
        static_configs:
        - targets: ['{{ include "union-operator.fullname" . }}-kube-state-metrics.{{ include "union-operator.namespace" . }}.svc.cluster.local:{{ .Values.union.unionoperatorMonitoring.kubeStateMetrics.service.port }}']
        metric_relabel_configs:
        - separator: ;
          source_labels: [__name__]
          regex: kube_pod_container_resource_limits|kube_pod_container_resource_requests|kube_pod_status_phase|kube_node_labels|kube_node_status_condition
          action: keep
      - job_name: 'gpu-metrics'
        static_configs:
        - targets: ['{{ include "union-operator.fullname" . }}-dcgm-exporter.{{ include "union-operator.namespace" . }}.svc.cluster.local:{{ .Values.union.unionoperatorMonitoring.dcgmExporter.service.port }}']
      - job_name: kubernetes-cadvisor
        metrics_path: /metrics
        scheme: https
        kubernetes_sd_configs:
        - api_server: null
          role: node
          namespaces:
            names: []
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: false
        metric_relabel_configs:
        - separator: ;
          source_labels: [__name__]
          regex: container_cpu_usage_seconds_total|container_memory_working_set_bytes
          action: keep
        relabel_configs:
        - separator: ;
          regex: __meta_kubernetes_node_label_(.+)
          replacement: $1
          action: labelmap
        - separator: ;
          regex: (.*)
          target_label: __address__
          replacement: kubernetes.default.svc:443
          action: replace
        - source_labels: [__meta_kubernetes_node_name]
          separator: ;
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
          action: replace
      {{- if and (.Values.union.unionoperatorMonitoring.opencost.enabled) (.Values.union.unionoperatorMonitoring.opencost.scrape) }}
      - job_name: 'opencost'
        honor_labels: true
        scrape_interval: 1m
        static_configs:
        - targets: ['opencost.{{ include "union-operator.namespace" . }}.svc.cluster.local:9003']
        metric_relabel_configs:
        - separator: ;
          source_labels: [__name__]
          regex: container_.*|.*_labels|.*_cost
          action: keep
      {{- end}}
  rules.yml: |
    groups:
      - name: rollup
        rules:
        - record: instance_type:kube_node_labels:sum
          expr: sum by (label_cloud_google_com_gke_accelerator, label_cloud_google_com_gke_preemptible, label_eks_amazonaws_com_capacity_type, label_flyte_org_node_role, label_node_group_name, label_node_kubernetes_io_instance_type, label_node_pool_name, label_topology_kubernetes_io_region) (kube_node_labels{job="kube-state-metrics"})
{{- end }}
