{{- if .Values.union.unionoperatorMonitoring.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "union-operator.fullname" . }}-prometheus
  labels:
    {{- include "unionoperatorMonitoring.prometheus.labels" . | nindent 4 }}
data:
  # Current config support scraping from configured kube state metrics service which serves request and limit metrics of
  # all the pods running in the data plane.(We will later restrict this to serve only from configured namespaces where
  # user pods are running). Also apart from request and limit it scrapes other metrics which come out of the box by installing
  # the service.We will further refine them to set of useful metrics that should be scraped in next iteration.
  # This installation of prometheus doesn't support scaling or retention and would be taken as immediate next step.
  # The scrape interval is of 15 sec from state metrics endpoint.
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
    rule_files:
    scrape_configs:
      - job_name: 'kube-state-metrics'
        static_configs:
        - targets: ['{{ include "union-operator.fullname" . }}-kube-state-metrics.{{ include "union-operator.namespace" . }}.svc.cluster.local:8080']
  {{- end }}
