{{- if .Values.union.unionoperatorMonitoring.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "union-operator.fullname" . }}-prometheus
  labels:
    {{- include "unionoperatorMonitoring.prometheus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.union.unionoperatorMonitoring.prometheus.autoscaling.enabled }}
  replicas: {{ index .Values.union.unionoperatorMonitoring.prometheus.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "unionoperatorMonitoring.prometheus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        configChecksum: {{ include (print .Template.BasePath "/monitoring/prometheus/configmap.yaml") . | sha256sum | trunc 63 | quote }}
      {{- with  .Values.union.unionoperatorMonitoring.prometheus.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "unionoperatorMonitoring.prometheus.selectorLabels" . | nindent 8 }}
    spec:
      priorityClassName: {{ .Values.union.unionoperatorMonitoring.prometheus.priorityClassName }}
      {{- with .Values.union.unionoperatorMonitoring.prometheus.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "unionoperatorMonitoring.prometheus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.union.unionoperatorMonitoring.prometheus.podSecurityContext | nindent 8 }}
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: '{{ include "union-operator.fullname" . }}-prometheus'
      containers:
        - args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.external-url=/prometheus/
          image: "{{ .Values.union.unionoperatorMonitoring.prometheus.image.repository }}:{{ .Values.union.unionoperatorMonitoring.prometheus.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.union.unionoperatorMonitoring.prometheus.image.pullPolicy }}
          name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.union.unionoperatorMonitoring.prometheus.securityContext | nindent 12 }}
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            {{- toYaml .Values.union.unionoperatorMonitoring.prometheus.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/prometheus
              name: prometheus-config-volume
          ports:
            - name: http
              containerPort: 18080
              protocol: TCP
      {{- with .Values.union.unionoperatorMonitoring.prometheus.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.union.unionoperatorMonitoring.prometheus.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.union.unionoperatorMonitoring.prometheus.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
