{{ if .Values.union.objectStore.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: object-store-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "union-operator.serviceAccountName" . }}
    namespace: {{ template "flyte.namespace" . }}
roleRef:
  kind: ClusterRole
  name: object-store-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}