{{ if .Values.union.objectStore.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "union-operator.fullname" . }}-object-store
  labels:
    {{- include "object-store.labels" . | nindent 4 }}
data:
  config.yaml: |
    sharedService:
      security:
        allowLocalhostAccess: true
      metrics:
        scope: objectstore
      grpc:
        maxMessageSizeBytes: {{ int (.Values.union.objectStore.maxMessageSizeBytes) }}
    objectStore:
      bucket: {{ tpl (.Values.union.objectStore.bucket | toString) $ }}
      redis:
        host: {{ tpl (.Values.union.objectStore.redis.host | toString) $ }}
      authorizationConfig:
        operatorDeploymentNamespace: {{ template "flyte.namespace" . }}
  logger.yaml: |
    logger:
      level: 6
      show-source: true
{{- with .Values.union.objectStore.configmapOverrides }}
  config-overrides.yaml: |
  {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
  storage.yaml: | {{ tpl (include "union-storage" .) $ | nindent 4 }}
 {{ end }}
