{{ if .Values.union.objectStore.enabled -}}
apiVersion: apps/v1
# TODO(haytham): Create a separate deployment for metadata store
kind: Deployment
metadata:
  name: {{ include "union-operator.fullname" . }}-object-store
  labels:
    {{- include "object-store.labels" . | nindent 4 }}
spec:
  {{- if not .Values.union.unionoperator.autoscaling.enabled }}
  replicas: {{ .Values.union.unionoperator.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "object-store.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        configChecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 | quote }}
      {{- with .Values.union.unionoperator.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "object-store.selectorLabels" . | nindent 8 }}
    spec:
      priorityClassName: {{ .Values.union.unionoperator.priorityClassName }}
      {{- with .Values.union.unionoperator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "union-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.union.unionoperator.podSecurityContext | nindent 8 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "union-operator.fullname" . }}-object-store
{{ if .Values.union.objectStore.secrets.mount }}
        - name: secrets
          secret:
            secretName: {{ include "union-operator.fullname" . }}-object-store
{{- end }}
      containers:
        - name: {{ .Chart.Name }}-object-store
          securityContext:
            {{- toYaml .Values.union.unionoperator.securityContext | nindent 12 }}
          image: "{{ .Values.union.unionoperator.image.repository }}:{{ .Values.union.unionoperator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.union.unionoperator.image.pullPolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            {{- toYaml .Values.union.unionoperator.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/union/config
              name: config-volume
{{ if .Values.union.objectStore.secrets.mount }}
            - mountPath: /etc/secrets/
              name: secrets
{{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEPLOYMENT_NAME
              value: {{ include "union-operator.fullname" . }}
          args:
            - objectstore
            - serve
            - --config
            - /etc/union/config/*.yaml
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
            - name: http
              containerPort: 8089
              protocol: TCP
            - name: debug
              containerPort: 10254
              protocol: TCP
      {{- with .Values.union.unionoperator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.union.unionoperator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.union.unionoperator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}