{{- if .Values.union.objectStore.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "union-operator.fullname" . }}-object-store
  labels:
    {{- include "object-store.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis_auth_token: {{ tpl .Values.union.objectStore.secrets.redisAuthToken . }}
{{- end }}
