{{- if .Values.union.unionoperatorMonitoring.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "union-operator.fullname" . }}-kube-state-metrics
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
    verbs: ["get", "list", "watch"]
{{- end }}