{{- if .Values.union.unionoperatorMonitoring.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics
subjects:
  - kind: ServiceAccount
    name: {{ include "unionoperatorMonitoring.kubeStateMetrics.serviceAccountName" . }}
    namespace: kube-system
{{- end }}