apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "union-operator.fullname" . }}
data:
  config.yaml: |
    union:
      connection:
        host: dns:///{{ .Values.settings.cloudUrl }}
      auth:
        type: ClientSecret
        clientId: {{ .Values.settings.appId }}
        clientSecretLocation: /etc/union/secret/app_secret
      clusterId:
        name: {{ include "clusterName" . }}
        organization: {{ (split "." .Values.settings.cloudUrl)._0 }}
