apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "union-operator.fullname" . }}
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
data:
  config.yaml: |
    union:
      connection:
        host: {{ include "union-operator.grpcUrl" . }}
      auth:
        type: ClientSecret
        clientId: {{ .Values.union.appId }}
        clientSecretLocation: /etc/union/secret/app_secret
    operator:
      clusterId:
        organization: {{ include "union-operator.org" . }}
{{- with .Values.configmapOverrides }}
  config-overrides.yaml: | {{ toYaml . | nindent 4 }}
{{- end }}
