apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "union-operator.fullname" . }}
data:
  config.yaml: |
    union:
      connection:
        host: dns:///{{ .Values.union.cloudUrl }}
      auth:
        type: ClientSecret
        clientId: {{ .Values.union.appId }}
        clientSecretLocation: /etc/union/secret/app_secret
    operator:
      clusterId:
        name: {{ include "clusterName" . }}
        organization: {{ (split "." .Values.union.cloudUrl)._0 }}
{{- with .Values.configmapOverrides }}
  config-overrides.yaml: | {{ toYaml . | nindent 4 }}
{{- end }}
