apiVersion: v1
kind: Service
metadata:
  name: {{ include "union-operator.fullname" . }}
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: debug
      protocol: TCP
      name: debug
  selector:
    {{- include "union-operator.selectorLabels" . | nindent 4 }}
