apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "union-operator.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.proxy.autoscaling.enabled }}
  replicas: {{ .Values.proxy.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.proxy.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "proxy.selectorLabels" . | nindent 8 }}
        {{- with .Values.proxy.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      volumes:
        - name: config-volume
          projected:
            sources:
            - configMap:
                name: {{ include "union-operator.fullname" . }}
            - configMap:
                name: flyte-clusterresourcesync-config
      priorityClassName: {{ .Values.proxy.priorityClassName | default "system-cluster-critical" }}
      {{- with .Values.proxy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.proxy.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-proxy
          securityContext:
            {{- toYaml .Values.proxy.securityContext | nindent 12 }}
          image: "{{ .Values.image.union.repository }}:{{ .Values.image.union.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.union.pullPolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/union/config
              name: config-volume
          args:
            - operator
            - proxy
            - --config
            - /etc/union/config/*.yaml
          ports:
            - name: http
              containerPort: 8089
              protocol: TCP
            - name: grpc
              containerPort: 8080
              protocol: TCP
            - name: debug
              containerPort: 10254
              protocol: TCP
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            {{- with .Values.proxy.podEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
