{{- if .Values.flyteagent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "flyteagent.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteagent.labels" . | nindent 4 }}
  {{- with .Values.flyteagent.service.annotations }}
  annotations: {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.flyteagent.service.clusterIP}}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    - name: {{ .Values.flyteagent.ports.name }}
      port: {{ .Values.flyteagent.ports.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.flyteagent.ports.name }}
    - name: {{ .Values.flyteagent.prometheusPort.name }}
      port: {{ .Values.flyteagent.prometheusPort.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.flyteagent.prometheusPort.name }}
  selector: {{ include "flyteagent.selectorLabels" . | nindent 4 }}
{{- end }}