name: Release helm
on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"


#
#  helm-release:
#    name: Unionoperator helm release
#    runs-on: ubuntu-latest
#    needs: [bump-version]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: "0"
#      - name: Install Helm
#        uses: azure/setup-helm@v1
#      - name: Update Version in helm
#        run: |
#          sed "s/v0.0.1/${{ needs.bump-version.outputs.version }}/g" ./charts/unionoperator/README.md  > temp.txt && mv temp.txt ./charts/unionoperator/README.md
#          grep -rlZ "version:[^P]*# VERSION" ./charts/unionoperator/Chart.yaml | xargs -0 sed -i "s/version:[^P]*# VERSION/version: ${{ needs.bump-version.outputs.version }} # VERSION/g"
#          grep -rlZ "appVersion:[^P]*# APP_VERSION" ./charts/unionoperator/Chart.yaml | xargs -0 sed -i "s/appVersion:[^P]*# APP_VERSION/appVersion: ${{ needs.bump-version.outputs.version }} # APP_VERSION/g"
#      - name: Configure Git
#        run: |
#          git config user.name "${{ github.actor }}"
#          git config user.email "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
#      - name: Run chart-releaser
#        uses: stefanprodan/helm-gh-pages@v1.4.1
#        with:
#          token: "${{ secrets.CI_BOT_PAT }}"
#          linting: off